version: '3'

services:
  db:
    image: postgres
    command: -p 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - data-volume:/var/lib/postgresql/data

  web:
    build: .
    environment:
      POSTGRES_DB: ecatalogue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5433
      POSTGRES_HOST: db
    ports:
      - "8080:8080"
    command: gunicorn application.wsgi:application --worker-connections=1000 --workers=9 --bind 0.0.0.0:8080
    links:
      - db
    depends_on:
      - db

volumes:
  data-volume: